Update it to use .config files for the runfile installer

diff --git a/.github/workflows/build_linux_runfile_installer.yml b/.github/workflows/build_linux_runfile_installer.yml
--- a/.github/workflows/build_linux_runfile_installer.yml
+++ b/.github/workflows/build_linux_runfile_installer.yml
@@ -4,7 +4,7 @@ on:
   workflow_call:
     inputs:
       rocm_version:
-        description: ROCm version used to build runfile installer (7.12.0~20260218 for nightly, 7.11.0~rc2 for 7.11 prerelease RC2 or 7.12.0 if you're triggering the job manually)
+        description: ROCm version used to build runfile installer (eg. 7.12.0)
         required: true
         type: string
       release_type:
@@ -14,14 +14,12 @@ on:
         default: "dev"
       gfx_archs:
         description: gfx architectures to build (eg "gfx90x", "gfx94x", "gfx950", "gfx110x", "gfx1150", "gfx1151", "gfx1152", "gfx120x")
-        required: true
+        required: false
         type: string
-        default: "gfx90x,gfx94x,gfx950,gfx110x,gfx1150,gfx1151,gfx1152,gfx120x"
       pull_amdgpu:
         description: Version of amdgpu to be packaged into runfile installer. To see valid values for parameter, run command "bash build-runfile-installer.sh help
-        required: true
+        required: false
         type: string
-        default: "release,31.10"
       pull_type:
         description: Specify where you want to pull packages from ("nightly" or "prereleases") which pull from rocm.nightlies.amd.com or rocm.prereleases.amd.com
         required: true
@@ -57,14 +55,12 @@ on:
         default: "dev"
       gfx_archs:
         description: gfx architectures to build (eg "gfx90x", "gfx94x", "gfx950", "gfx110x", "gfx1150", "gfx1151", "gfx1152", "gfx120x")
-        required: true
+        required: false
         type: string
-        default: "gfx90x,gfx94x,gfx950,gfx110x,gfx1150,gfx1151,gfx1152,gfx120x"
       pull_amdgpu:
         description: Version of amdgpu to be packaged into runfile installer.
-        required: true
+        required: false
         type: string
-        default: "release,31.10"
       pull_type:
         description: Specify where you want to pull packages from, which pull from rocm.nightlies.amd.com or rocm.prereleases.amd.com
         type: choice
@@ -85,6 +81,17 @@ on:
         required: false
         type: string
         default: "amdrocm-core-sdk"
+      runfile_config:
+        description: Runfile config file to use (leave empty to use default based on release_type)
+        required: false
+        type: choice
+        options:
+          - ""
+          - dev.config
+          - nightly.config
+          - prerelease.config
+          - release.config
+        default: ""
 permissions:
   id-token: write
   contents: read
@@ -116,57 +123,46 @@ jobs:
       BUILD_TAG: ${{ inputs.pull_tag }}
       GFX_ARCHS: ${{ inputs.gfx_archs }}
       PULL_AMDGPU: ${{ inputs.pull_amdgpu }}
+      # If users enters dev.config for runfile_config, then this becomes
+      # config/dev.config
+
+      # If user leaves runfile_config empty and sets release_type to be nightly, then this becomes
+      # config/nightly.config
+      RUNFILE_CONFIG: ${{ inputs.runfile_config && format('config/{0}', inputs.runfile_config) || format('config/{0}.config', inputs.release_type) }}
       S3_BUCKET_RUNFILE: therock-${{ inputs.release_type }}-runfile
     steps:
       - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+         
+      - name: Set BUILD_TAG for dev branch
+        if: ${{ env.RELEASE_TYPE == 'dev' }}
+        run: |
+          git config --global --add safe.directory "$GITHUB_WORKSPACE"
+          BUILD_TAG="dev-$(git rev-parse --short HEAD)"
+          echo "Set value of BUILD_TAG = '$BUILD_TAG'"
+          echo "BUILD_TAG=$BUILD_TAG" >> $GITHUB_ENV
       
-      # - name: Set ROCM_VERSION
-      #   run: |
-      #     ROCM_VERSION=$(echo "${{ inputs.rocm_version }}" | cut -d'~' -f1)
-      #     echo "Set value of ROCM_VERSION = '$ROCM_VERSION'"
-      #     echo "ROCM_VERSION=$ROCM_VERSION" >> $GITHUB_ENV
-      
-      # # Value of inputs.rocm_version for daily nightly job would be in the format 7.12.0~20260218.
-      # # We need the 20260218 and set it to pull_tag
-      # # Value of inputs.rocm_version for prerelease job would be in the format 7.12.0~rc2.
-      # # We need the rc2 and set it to pull_tag.
-      # - name: Set PULL_TAG
-      #   run: |
-      #     if [[ -z $PULL_TAG ]]; then
-      #       PULL_TAG=$(echo "${{ inputs.rocm_version }}" | cut -d'~' -f2)
-      #       echo "Set value of PULL_TAG = '$PULL_TAG'"
-      #       echo "PULL_TAG=$PULL_TAG" >> $GITHUB_ENV
-      #     fi
-        
-      # - name: Set MSCOMP
-      #   run: |
-      #     if [[ $RELEASE_TYPE == "dev" ]]; then
-      #       MSCOMP=dev
-      #     else
-      #       MSCOMP=prodmedium
-      #     fi
-      #     echo "Set value of MSCOMP = '$MSCOMP'"
-      #     echo "MSCOMP=$MSCOMP" >> $GITHUB_ENV
-      
-      # - name: Set BUILD_TAG for dev branch
-      #   if: ${{ env.RELEASE_TYPE == 'dev' }}
-      #   run: |
-      #     git config --global --add safe.directory "$GITHUB_WORKSPACE"
-      #     BUILD_TAG="dev-$(git rev-parse --short HEAD)"
-      #     echo "Set value of BUILD_TAG = '$BUILD_TAG'"
-      #     echo "BUILD_TAG=$BUILD_TAG" >> $GITHUB_ENV
+      - name: Build args
+        run: |
+          args=""
+          if [[ -n "$GFX_ARCHS" ]]; then
+            args="$args rocm-archs=$GFX_ARCHS"
+          fi
+          if [[ -n "$PULL_AMDGPU" ]]; then
+            args="$args pullamdgpu=$PULL_AMDGPU"
+          fi
+          echo "ARGS=$args" >> $GITHUB_ENV
 
-      # - name: Run build-runfile-installer.sh
-      #   run: |
-      #     echo "### Runfile Build Options" >> $GITHUB_STEP_SUMMARY
-      #     echo "" >> $GITHUB_STEP_SUMMARY
+      - name: Run build-runfile-installer.sh
+        run: |
+          echo "### Runfile Build Options" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
 
-      #     echo "\`bash build-runfile-installer.sh rocm amdgpu rocm-archs=$GFX_ARCHS pullamdgpu=$PULL_AMDGPU pull=$PULL_TYPE pulltag=$PULL_TAG pullrunid=$PULL_RUN_ID pullrocmver=$ROCM_VERSION pullpkg=$PULL_PKG buildtag=$BUILD_TAG buildrunid=$BUILD_RUNID mscomp=$MSCOMP\`" >> $GITHUB_STEP_SUMMARY
+          echo "\`bash build-runfile-installer.sh config=$RUNFILE_CONFIG_FILE rocm amdgpu pull=$PULL_TYPE pulltag=$PULL_TAG pullrunid=$PULL_RUN_ID pullrocmver=$ROCM_VERSION pullpkg=$PULL_PKG buildtag=$BUILD_TAG buildrunid=$BUILD_RUNID $ARGS\`" >> $GITHUB_STEP_SUMMARY
           
-      #     bash build-runfile-installer.sh rocm amdgpu rocm-archs=$GFX_ARCHS pullamdgpu=$PULL_AMDGPU pull=$PULL_TYPE pulltag=$PULL_TAG pullrunid=$PULL_RUN_ID pullrocmver=$ROCM_VERSION pullpkg=$PULL_PKG buildtag=$BUILD_TAG buildrunid=$BUILD_RUNID mscomp=$MSCOMP
+          bash build-runfile-installer.sh config=$RUNFILE_CONFIG_FILE rocm amdgpu pull=$PULL_TYPE pulltag=$PULL_TAG pullrunid=$PULL_RUN_ID pullrocmver=$ROCM_VERSION pullpkg=$PULL_PKG buildtag=$BUILD_TAG buildrunid=$BUILD_RUNID $ARGS
 
-      # - name: Show .run file
-      #   run: find . -name "*.run" -type f -exec ls -lctrh {} \;
+      - name: Show .run file
+        run: find . -name "*.run" -type f -exec ls -lctrh {} \;
 
       - name: Install AWS CLI
         working-directory: ${{ github.workspace }}
@@ -179,30 +175,30 @@ jobs:
           aws-region: us-east-1
           role-to-assume: arn:aws:iam::317668459450:role/therock-${{ env.RELEASE_TYPE }}-runfile-s3-oidc
 
-      # - name: Upload runfile to S3
-      #   if: ${{ github.repository_owner == 'ROCm' }}    
-      #   run: |
-      #     RUNFILE=$(find . -name "*.run" -type f | head -1)
-      #     if [ -z "$RUNFILE" ]; then
-      #       echo "ERROR: No .run file found"
-      #       exit 1
-      #     fi
-      #     RUNFILE_NAME=$(basename "$RUNFILE")
-      #     echo "Uploading $RUNFILE to s3://${{ env.S3_BUCKET_RUNFILE }}/"
-      #     aws s3 cp "$RUNFILE" "s3://${{ env.S3_BUCKET_RUNFILE }}/"
+      - name: Upload runfile to S3
+        if: ${{ github.repository_owner == 'ROCm' }}    
+        run: |
+          RUNFILE=$(find . -name "*.run" -type f | head -1)
+          if [ -z "$RUNFILE" ]; then
+            echo "ERROR: No .run file found"
+            exit 1
+          fi
+          RUNFILE_NAME=$(basename "$RUNFILE")
+          echo "Uploading $RUNFILE to s3://${{ env.S3_BUCKET_RUNFILE }}/"
+          aws s3 cp "$RUNFILE" "s3://${{ env.S3_BUCKET_RUNFILE }}/"
           
-      #     # Append to GitHub Actions summary
-      #     echo "### Runfile Uploaded to S3" >> $GITHUB_STEP_SUMMARY
-      #     echo "" >> $GITHUB_STEP_SUMMARY
-      #     echo "**File:** \`${RUNFILE_NAME}\`" >> $GITHUB_STEP_SUMMARY
-      #     echo "" >> $GITHUB_STEP_SUMMARY
-      #     echo "**S3 Bucket:** \`${{ env.S3_BUCKET_RUNFILE }}\`" >> $GITHUB_STEP_SUMMARY
+          # Append to GitHub Actions summary
+          echo "### Runfile Uploaded to S3" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "**File:** \`${RUNFILE_NAME}\`" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "**S3 Bucket:** \`${{ env.S3_BUCKET_RUNFILE }}\`" >> $GITHUB_STEP_SUMMARY
       
-      # - name: Generate index.html needed to display runfile installers.
-      #   if: ${{ github.repository_owner == 'ROCm' }}
-      #   working-directory: ${{ github.workspace }}/build_tools
-      #   run: |
-      #     python -m venv .venv
-      #     source .venv/bin/activate
-      #     pip install boto3
-      #     python index_generation_s3_runfile.py --bucket ${{ env.S3_BUCKET_RUNFILE }} --upload
+      - name: Generate index.html needed to display runfile installers.
+        if: ${{ github.repository_owner == 'ROCm' }}
+        working-directory: ${{ github.workspace }}/build_tools
+        run: |
+          python -m venv .venv
+          source .venv/bin/activate
+          pip install boto3
+          python index_generation_s3_runfile.py --bucket ${{ env.S3_BUCKET_RUNFILE }} --upload
