Test env vars

diff --git a/.github/workflows/build_portable_linux_pytorch_wheels.yml b/.github/workflows/build_portable_linux_pytorch_wheels.yml
--- a/.github/workflows/build_portable_linux_pytorch_wheels.yml
+++ b/.github/workflows/build_portable_linux_pytorch_wheels.yml
@@ -99,66 +99,66 @@ jobs:
             --python-version ${{ inputs.python_version }}
           echo "cp_version=${{ env.cp_version }}" >> "$GITHUB_OUTPUT"
 
-      - name: Add selected Python version to PATH
-        run: |
-          python_dir="/opt/python/${{ env.cp_version }}"
-          if ! [ -x "${python_dir}/bin/python" ]; then
-            echo "ERROR: Could not find python: ${python_dir}"
-            exit 1
-          fi
-          echo "${python_dir}/bin" >> "$GITHUB_PATH"
+      # - name: Add selected Python version to PATH
+      #   run: |
+      #     python_dir="/opt/python/${{ env.cp_version }}"
+      #     if ! [ -x "${python_dir}/bin/python" ]; then
+      #       echo "ERROR: Could not find python: ${python_dir}"
+      #       exit 1
+      #     fi
+      #     echo "${python_dir}/bin" >> "$GITHUB_PATH"
 
-      - name: Checkout PyTorch Source Repos
-        run: |
-          ./external-builds/pytorch/pytorch_torch_repo.py checkout
-          ./external-builds/pytorch/pytorch_audio_repo.py checkout
-          ./external-builds/pytorch/pytorch_vision_repo.py checkout
+      # - name: Checkout PyTorch Source Repos
+      #   run: |
+      #     ./external-builds/pytorch/pytorch_torch_repo.py checkout
+      #     ./external-builds/pytorch/pytorch_audio_repo.py checkout
+      #     ./external-builds/pytorch/pytorch_vision_repo.py checkout
 
-      - name: Create pip cache directory
-        run: mkdir -p /tmp/pipcache
+      # - name: Create pip cache directory
+      #   run: mkdir -p /tmp/pipcache
 
-      - name: Determine optional arguments passed to `build_prod_wheels.py`
-        if: ${{ inputs.rocm_version }}
-        run: |
-          pip install packaging
-          python build_tools/github_actions/determine_version.py \
-            --rocm-version ${{ inputs.rocm_version }}
+      # - name: Determine optional arguments passed to `build_prod_wheels.py`
+      #   if: ${{ inputs.rocm_version }}
+      #   run: |
+      #     pip install packaging
+      #     python build_tools/github_actions/determine_version.py \
+      #       --rocm-version ${{ inputs.rocm_version }}
 
-      - name: Build PyTorch Wheels
-        id: build-pytorch-wheels
-        run: |
-          echo "Building PyTorch wheels for ${{ inputs.amdgpu_family }}"
-          ./external-builds/pytorch/build_prod_wheels.py \
-            build \
-            --install-rocm \
-            --pip-cache-dir /tmp/pipcache \
-            --index-url "${{ inputs.cloudfront_url }}/${{ inputs.amdgpu_family }}/" \
-            --clean \
-            --output-dir ${{ env.PACKAGE_DIST_DIR }} ${{ env.optional_build_prod_arguments }}
-          echo "torch_version=`cd ${{ env.PACKAGE_DIST_DIR }}; python -c 'import glob; print(glob.glob("torch-*.whl")[0].split("-")[1])'`" >> $GITHUB_OUTPUT
+      # - name: Build PyTorch Wheels
+      #   id: build-pytorch-wheels
+      #   run: |
+      #     echo "Building PyTorch wheels for ${{ inputs.amdgpu_family }}"
+      #     ./external-builds/pytorch/build_prod_wheels.py \
+      #       build \
+      #       --install-rocm \
+      #       --pip-cache-dir /tmp/pipcache \
+      #       --index-url "${{ inputs.cloudfront_url }}/${{ inputs.amdgpu_family }}/" \
+      #       --clean \
+      #       --output-dir ${{ env.PACKAGE_DIST_DIR }} ${{ env.optional_build_prod_arguments }}
+      #     echo "torch_version=`cd ${{ env.PACKAGE_DIST_DIR }}; python -c 'import glob; print(glob.glob("torch-*.whl")[0].split("-")[1])'`" >> $GITHUB_OUTPUT
 
-      - name: Configure AWS Credentials
-        if: always()
-        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
-        with:
-          aws-region: us-east-2
-          role-to-assume: arn:aws:iam::692859939525:role/therock-${{ inputs.release_type }}-releases
+      # - name: Configure AWS Credentials
+      #   if: always()
+      #   uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
+      #   with:
+      #     aws-region: us-east-2
+      #     role-to-assume: arn:aws:iam::692859939525:role/therock-${{ inputs.release_type }}-releases
 
-      - name: Sanity Check Wheel
-        run: |
-          python external-builds/pytorch/sanity_check_wheel.py ${{ env.PACKAGE_DIST_DIR }}/
+      # - name: Sanity Check Wheel
+      #   run: |
+      #     python external-builds/pytorch/sanity_check_wheel.py ${{ env.PACKAGE_DIST_DIR }}/
 
-      - name: Upload wheels to staging S3
-        if: ${{ github.repository_owner == 'ROCm' }}
-        run: |
-          aws s3 cp ${{ env.PACKAGE_DIST_DIR }}/ s3://${{ env.S3_BUCKET_PY }}/${{ inputs.s3_staging_subdir }}/${{ inputs.amdgpu_family }}/ \
-            --recursive --exclude "*" --include "*.whl"
+      # - name: Upload wheels to staging S3
+      #   if: ${{ github.repository_owner == 'ROCm' }}
+      #   run: |
+      #     aws s3 cp ${{ env.PACKAGE_DIST_DIR }}/ s3://${{ env.S3_BUCKET_PY }}/${{ inputs.s3_staging_subdir }}/${{ inputs.amdgpu_family }}/ \
+      #       --recursive --exclude "*" --include "*.whl"
 
-      - name: (Re-)Generate Python package release index
-        if: ${{ github.repository_owner == 'ROCm' }}
-        run: |
-          pip install boto3 packaging
-          python ./build_tools/third_party/s3_management/manage.py ${{ inputs.s3_staging_subdir }}/${{ inputs.amdgpu_family }}
+      # - name: (Re-)Generate Python package release index
+      #   if: ${{ github.repository_owner == 'ROCm' }}
+      #   run: |
+      #     pip install boto3 packaging
+      #     python ./build_tools/third_party/s3_management/manage.py ${{ inputs.s3_staging_subdir }}/${{ inputs.amdgpu_family }}
 
   generate_target_to_run:
     name: Generate target_to_run
@@ -175,25 +175,28 @@ jobs:
           TARGET: ${{ inputs.amdgpu_family }}
         run: python ./build_tools/github_actions/configure_target_run.py
 
-  test_pytorch_wheels:
-    if: ${{ needs.generate_target_to_run.outputs.test_runs_on != '' }}
-    needs: [build_pytorch_wheels, generate_target_to_run]
-    uses: ./.github/workflows/test_pytorch_wheels.yml
-    with:
-      amdgpu_family: ${{ inputs.amdgpu_family }}
-      test_runs_on: ${{ needs.generate_target_to_run.outputs.test_runs_on }}
-      cloudfront_url: ${{ inputs.cloudfront_staging_url }}
-      python_version: ${{ inputs.python_version }}
-      torch_version: ${{ needs.build_pytorch_wheels.outputs.torch_version }}
+  # test_pytorch_wheels:
+  #   if: ${{ needs.generate_target_to_run.outputs.test_runs_on != '' }}
+  #   needs: [build_pytorch_wheels, generate_target_to_run]
+  #   uses: ./.github/workflows/test_pytorch_wheels.yml
+  #   with:
+  #     amdgpu_family: ${{ inputs.amdgpu_family }}
+  #     test_runs_on: ${{ needs.generate_target_to_run.outputs.test_runs_on }}
+  #     cloudfront_url: ${{ inputs.cloudfront_staging_url }}
+  #     python_version: ${{ inputs.python_version }}
+  #     torch_version: ${{ needs.build_pytorch_wheels.outputs.torch_version }}
 
   upload_pytorch_wheels:
     name: Upload PyTorch Wheels to S3
-    needs: [build_pytorch_wheels, generate_target_to_run, test_pytorch_wheels]
+    # needs: [build_pytorch_wheels, generate_target_to_run, test_pytorch_wheels]
+    needs: [build_pytorch_wheels, generate_target_to_run]
     if: success() && github.repository_owner == 'ROCm'
     runs-on: ubuntu-24.04
     env:
       PACKAGE_DIST_DIR: ${{ github.workspace }}/output/packages/dist
       S3_BUCKET_PY: "therock-${{ inputs.release_type }}-python"
+      CP_VERSION: ${{ needs.build_pytorch_wheels.outputs.cp_version }}
+
     steps:
       - name: Checkout
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
@@ -208,7 +211,7 @@ jobs:
       - name: Copy only tested PyTorch wheels from staging to release S3
         run: |
           torch_version="${{ needs.build_pytorch_wheels.outputs.torch_version }}"
-          cp_version="${{ needs.build_pytorch_wheels.outputs.cp_version }}"
+          cp_version="${CP_VERSION}"
           echo "Torch version: $torch_version"
           # Extract the ROCm suffix from the torch version (everything after '+')
           rocm_suffix=$(echo "$torch_version" | cut -d '+' -f 2)
