Read and propagate exit code.

diff --git a/.github/workflows/test_pytorch_wheels.yml b/.github/workflows/test_pytorch_wheels.yml
--- a/.github/workflows/test_pytorch_wheels.yml
+++ b/.github/workflows/test_pytorch_wheels.yml
@@ -145,8 +145,29 @@ jobs:
           pytest --log-cli-level=INFO -v external-builds/pytorch/smoke-tests
 
       # TODO: rename to run_pytorch_tests.py (shared between Windows and Linux)
-      - name: Run PyTorch tests
+      - name: (Linux) Run PyTorch tests
+        if: ${{ contains(inputs.test_runs_on, 'linux') }}
         run: |
           python ./external-builds/pytorch/run_linux_pytorch_tests.py
 
-      # TODO: read retcode.txt result Windows, return that status (pass/fail the job)
+      # HACK: The test process does not terminate on its own gracefully,
+      # so we write to exit_code.txt and then kill the process.
+      # After killing the process we read the return code to signal it normally.
+      # See https://github.com/ROCm/TheRock/issues/999.
+      - name: (Windows) Run PyTorch tests
+        if: ${{ contains(inputs.test_runs_on, 'windows') }}
+        continue-on-error: true
+        run: |
+          python ./external-builds/pytorch/run_linux_pytorch_tests.py
+
+      - name: (Windows) Read and propagate exit code
+        shell: bash
+        run: |
+          if [ -f exit_code.txt ]; then
+            EXIT_CODE=$(cat exit_code.txt)
+            echo "Exit code from file: $EXIT_CODE"
+            exit $EXIT_CODE
+          else
+            echo "No exit_code.txt found"
+            exit 1
+          fi
